/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_homework;

import java.util.Scanner;

public class Solution {

    public static void main(String[] args) {

        Scanner in = new Scanner(System.in);
        System.out.println("Введите любую строку");
        String line = in.nextLine();
        System.out.println("Результат: "+ shrink_space(line));
        in.close();
    }

    public static String shrink_space(String input) {
        String result = "";
        for(int i=0; i < input.length()-1; i++) {
            if ((input.charAt(i) == ' ')&&(input.charAt(i+1) == ' ')){
                continue;
            }
            else {
                result += input.charAt(i);
            }
        }
        if (input.length() - 1 >= 0)
            result += input.charAt(input.length()-1);
        return result;
    }
}
